name: Test Front and Back

on:
      push:
            branches: ['main']
      pull_request:
            branches: ['main']

permissions:
      contents: write

jobs:
      angular:
            name: Front
            runs-on: ubuntu-latest
            strategy:
                  matrix:
                        node-version: [20]
            steps:
                  - name: Check source code
                    uses: actions/checkout@v4

                  - name: Setup Node
                    uses: actions/setup-node@v4
                    with:
                          node-version: 20
                          cache: 'npm'
                          cache-dependency-path: package-lock.json

                  - name: Install dependencies
                    run: npm ci
                    working-directory: front

                  - name: Run tests
                    run: npm run test  -- --browsers=ChromeHeadlessNoSandbox
                    working-directory: front

                  - name: Upload report
                    uses: actions/upload-artifact@v4
                    with:
                          name: karma-report
                          path: front/coverage/bobapp

                  - name: Pull last changes
                    run: |
                          git config --local user.email "github-actions[bot]@users.noreply.github.com"
                          git config --local user.name "github-actions[bot]"
                          git pull origin main

                  - name: Commit report
                    run: |
                          git add front/coverage/bobapp
                          git commit -m "Add Karma report"

                  - name: Push Karma report
                    uses: ad-m/github-push-action@master
                    with:
                          github_token: ${{ secrets.GIT_TOKEN }}
                          branch: ${{ github.ref }}

                  - name: SonarCloud Scan
                    uses: SonarSource/sonarcloud-github-action@master
                    env:
                          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }} # Needed to get PR information, if any
                          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    with:
                          projectBaseDir: ./front

      java:
            name: Spring Boot
            runs-on: ubuntu-latest
            steps:
                  - name: Checkout the source code
                    uses: actions/checkout@v4

                  - name: Set up JDK 17
                    uses: actions/setup-java@v4
                    with:
                          distribution: 'adopt'
                          java-version: '17'

                  - name: Install dependencies
                    run: mvn clean install
                    working-directory: back

                  - name: Run tests
                    run: mvn test
                    working-directory: back

                  - name: Generate Jacoco report
                    run: mvn jacoco:report
                    working-directory: back

                  - name: Upload Jacoco report
                    uses: actions/upload-artifact@v4
                    with:
                          name: jacoco-report
                          path: back/target/site/jacoco

                  - name: Pull latest changes
                    run: |
                          git config --local user.email "github-actions[bot]@users.noreply.github.com"
                          git config --local user.name "github-actions[bot]"
                          git pull origin main

                  - name: Commit Jacoco report
                    run: |
                          git add -f back/target/site/jacoco
                          git commit -m "Add Jacoco report"

                  - name: Push Jacoco report
                    uses: ad-m/github-push-action@master
                    with:
                          github_token: ${{ secrets.GIT_TOKEN }}
                          branch: ${{ github.ref }}

                  - name: Cache SonarCloud packages
                    uses: actions/cache@v4
                    with:
                          path: ~/.sonar/cache
                          key: ${{ runner.os }}-sonar
                          restore-keys: ${{ runner.os }}-sonar

                  - name: Cache Maven packages
                    uses: actions/cache@v4
                    with:
                          path: ~/.m2
                          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                          restore-keys: ${{ runner.os }}-m2

                  - name: Build and test with Maven
                    run: mvn -B clean verify
                    working-directory: back

                  - name: SonarCloud Scan
                    env:
                          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

                    run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=bobappBack -Dsonar.projectName="BobApp Backend" -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml -Dsonar.tests=src/test/java -Dsonar.java.binaries=target/classes -Dsonar.language=java
                    working-directory: back
